services:
  app:
    image: ulemooss/news_aggregator_app:latest
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_URL: ${DATABASE_URL}
      NEWS_API_KEY: ${NEWS_API_KEY}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports:
      - "3000:3000"