default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV['POSTGRES_USER'] || 'user' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'user' %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] || 'news_aggregator_development' %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] || 'news_aggregator_test' %>

production:
  url: <%= ENV['DATABASE_URL'] %>
